<a href="https://colab.research.google.com/github/HappySkyLee/wia10007-datascience/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2],[3,4]]);
print("1.\n",array)

1.
 [[1 2]
 [3 4]]


In [3]:
random_array = np.random.rand(2,2);
print("2.\n",random_array);

2.
 [[0.086194   0.30782876]
 [0.31702931 0.58198598]]


In [4]:
zero_array = np.ones((2,2));
one_array = np.zeros((2,2));
print("3.\n",zero_array);
print("\n",one_array);

3.
 [[1. 1.]
 [1. 1.]]

 [[0. 0.]
 [0. 0.]]


In [5]:
array6x3 = np.random.randint(1,10,size=(6,3));
print("4.\n",array6x3);
array6x3_tranpose = array6x3.T;
print("\n",array6x3_tranpose);

4.
 [[7 3 1]
 [3 7 7]
 [7 9 2]
 [6 9 5]
 [6 8 3]
 [5 6 3]]

 [[7 3 7 6 6 5]
 [3 7 9 9 8 6]
 [1 7 2 5 3 3]]


In [6]:
n = int(input("Enter the number of row of the 1st array: "));
p = int(input("Enter the number of column of the 1st array or the number of row of the 2nd array: "));
m = int(input("Enter the number of column of the 2nd array: "));
Array_nxp = np.random.rand(n,p);
Array_pxm = np.random.rand(p,m);
dot_product = np.dot(Array_nxp,Array_pxm);
print("5.\n1st array\n",Array_nxp);
print("\n2nd array\n",Array_pxm);
print("\nDot Product:\n",dot_product);

Enter the number of row of the 1st array: 2
Enter the number of column of the 1st array or the number of row of the 2nd array: 1
Enter the number of column of the 2nd array: 2
5.
1st array
 [[0.10296149]
 [0.73845116]]

2nd array
 [[0.82740526 0.470264  ]]

Dot Product:
 [[0.08519088 0.04841908]
 [0.61099837 0.34726699]]
